// Builds backend/src/modules/words/data/phrases.{es,en}.json for "Adivina la frase"
// (docs/context/06-v1.1.md -> Guess the phrase). The banks are curated by hand
// right here: sayings and everyday expressions, 4 to 8 words, 16 to 42 letters,
// no proper nouns. The script only validates and writes; every line was
// reviewed like the word lists. Run: node scripts/build-phrases.mjs
import { writeFileSync } from 'node:fs';
import path from 'node:path';

const here = path.dirname(new URL(import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1'));
const out = path.join(here, '..', 'backend', 'src', 'modules', 'words', 'data');

const ES = [
  'a caballo regalado no le mires el diente',
  'a buen entendedor pocas palabras bastan',
  'a quien madruga dios le ayuda',
  'al mal tiempo buena cara',
  'más vale tarde que nunca',
  'más vale pájaro en mano que ciento volando',
  'no hay mal que por bien no venga',
  'el que ríe último ríe mejor',
  'ojos que no ven corazón que no siente',
  'en boca cerrada no entran moscas',
  'a palabras necias oídos sordos',
  'no por mucho madrugar amanece más temprano',
  'quien mucho abarca poco aprieta',
  'dime con quién andas y te diré quién eres',
  'a lo hecho pecho',
  'camarón que se duerme se lo lleva la corriente',
  'perro que ladra no muerde',
  'más vale prevenir que curar',
  'el que busca encuentra',
  'no todo lo que brilla es oro',
  'en casa de herrero cuchillo de palo',
  'de tal palo tal astilla',
  'el hábito no hace al monje',
  'cría cuervos y te sacarán los ojos',
  'donde hay humo hay fuego',
  'la curiosidad mató al gato',
  'las paredes tienen oídos',
  'la esperanza es lo último que se pierde',
  'a río revuelto ganancia de pescadores',
  'quien siembra vientos recoge tempestades',
  'no hay peor sordo que el que no quiere oír',
  'cada loco con su tema',
  'el tiempo lo cura todo',
  'nunca es tarde si la dicha es buena',
  'lo barato sale caro',
  'a falta de pan buenas son tortas',
  'quien no arriesga no gana',
  'la unión hace la fuerza',
  'el que la sigue la consigue',
  'no hay rosa sin espinas',
  'sobre gustos no hay nada escrito',
  'a cada cerdo le llega su san martín',
  'del dicho al hecho hay mucho trecho',
  'más vale maña que fuerza',
  'una golondrina no hace verano',
  'quien calla otorga',
  'la práctica hace al maestro',
  'no dejes para mañana lo que puedas hacer hoy',
  'zapatero a tus zapatos',
  'el mundo es un pañuelo',
  'a grandes males grandes remedios',
  'tanto va el cántaro a la fuente que al final se rompe',
  'el que no llora no mama',
  'donde fueres haz lo que vieres',
  'agua que no has de beber déjala correr',
  'hablando del rey de roma por la puerta asoma',
  'a otro perro con ese hueso',
  'quien tiene boca se equivoca',
  'las apariencias engañan',
  'no es oro todo lo que reluce',
  'poco a poco se va lejos',
  'la fe mueve montañas',
  'a mal tiempo buena cara',
  'cuando el río suena agua lleva',
  'de noche todos los gatos son pardos',
  'el saber no ocupa lugar',
  'ir por lana y volver trasquilado',
  'la mentira tiene las patas cortas',
  'más vale solo que mal acompañado',
  'no hay dos sin tres',
  'quien bien te quiere te hará llorar',
  'a buen hambre no hay pan duro',
  'cada oveja con su pareja',
  'con paciencia se gana el cielo',
  'el amor es ciego',
  'en el pecado está la penitencia',
  'la ocasión la pintan calva',
  'muerto el perro se acabó la rabia',
  'no hay enemigo pequeño',
  'quien fue a sevilla perdió su silla',
  'roma no se hizo en un día',
  'un clavo saca otro clavo',
  'ver para creer',
  'a caballo regalado no se le mira el colmillo',
  'al pan pan y al vino vino',
  'aunque la mona se vista de seda mona se queda',
  'barriga llena corazón contento',
  'con la vara que midas serás medido',
  'cuentas claras conservan amistades',
  'desde que el mundo es mundo',
  'echar leña al fuego',
  'el que avisa no es traidor',
  'el que espera desespera',
  'el que no corre vuela',
  'entre col y col lechuga',
  'estar en la luna de valencia',
  'hacer de tripas corazón',
  'hasta el rabo todo es toro',
  'hay más días que longanizas',
  'ir al grano sin rodeos',
  'la avaricia rompe el saco',
  'la cabra siempre tira al monte',
  'la sangre no llega al río',
  'la suerte está echada',
  'los últimos serán los primeros',
  'matar dos pájaros de un tiro',
  'meter la pata hasta el fondo',
  'no hay que buscarle tres pies al gato',
  'no se ganó zamora en una hora',
  'no vendas la piel del oso antes de cazarlo',
  'ponerse las pilas de una vez',
  'quedarse con la boca abierta',
  'quien mal anda mal acaba',
  'quien roba a un ladrón tiene cien años de perdón',
  'ser pan comido',
  'tirar la casa por la ventana',
  'tomar el pelo a alguien',
  'una imagen vale más que mil palabras',
  'vivir para ver',
  'a la tercera va la vencida',
  'a las pruebas me remito',
  'a rey muerto rey puesto',
  'agua pasada no mueve molino',
  'al que le pique que se rasque',
  'año nuevo vida nueva',
  'buscar una aguja en un pajar',
  'cada maestrillo tiene su librillo',
  'cambiar de chaqueta',
  'casa con dos puertas mala es de guardar',
  'como anillo al dedo',
  'como perro y gato',
  'con el tiempo y la paciencia todo se alcanza',
  'costar un ojo de la cara',
  'cuando las ranas críen pelo',
  'dar en el clavo',
  'dar gato por liebre',
  'de perdidos al río',
  'dormirse en los laureles',
  'el cliente siempre tiene la razón',
  'el fin justifica los medios',
  'el hombre propone y dios dispone',
  'el que parte y reparte se lleva la mejor parte',
  'el que tiene tienda que la atienda',
  'en abril aguas mil',
  'en tierra de ciegos el tuerto es rey',
  'errar es humano',
  'estar como pez en el agua',
  'estar en las nubes',
  'genio y figura hasta la sepultura',
  'hablar por los codos',
  'hacer la vista gorda',
  'hay ropa tendida',
  'la carne es débil',
  'la gota que colma el vaso',
  'la letra con sangre entra',
  'la tercera es la vencida',
  'lo prometido es deuda',
  'los niños y los borrachos siempre dicen la verdad',
  'mal de muchos consuelo de tontos',
  'mañana será otro día',
  'más vale un toma que dos te daré',
  'mucho ruido y pocas nueces',
  'no hay mal que dure cien años',
  'no hay que llorar sobre la leche derramada',
  'no pierdas el norte',
  'no tener pelos en la lengua',
  'nunca digas de esta agua no beberé',
  'ojo por ojo diente por diente',
  'pagar los platos rotos',
  'para gustos los colores',
  'pedir peras al olmo',
  'perder los estribos',
  'poner toda la carne en el asador',
  'quien no se arriesga no cruza el mar',
  'quien tiene un amigo tiene un tesoro',
  'salir de guatemala y meterse en guatepeor',
  'ser la oveja negra de la familia',
  'ser uña y carne',
  'tener la sartén por el mango',
  'tirar la toalla antes de tiempo',
  'todos los caminos llevan a roma',
  'un mal día lo tiene cualquiera',
  'una de cal y otra de arena',
  'vale más la salud que el dinero',
  'ver la luz al final del túnel',
  'a lo hecho pecho y a lo pasado olvidado',
  'al que madruga le da tiempo a todo',
  'amor con amor se paga',
  'aprendiz de todo maestro de nada',
  'arrieros somos y en el camino nos encontraremos',
  'bicho malo nunca muere',
  'buenas palabras no rompen huesos',
  'cada cual sabe dónde le aprieta el zapato',
  'cada uno en su casa y dios en la de todos',
  'caminante no hay camino se hace camino al andar',
  'cielo empedrado suelo mojado',
  'contigo pan y cebolla',
  'cuando una puerta se cierra otra se abre',
  'cuentas claras y el chocolate espeso',
  'de grandes cenas están las sepulturas llenas',
  'de músico poeta y loco todos tenemos un poco',
  'dios aprieta pero no ahoga',
  'dios los cría y ellos se juntan',
  'donde menos se piensa salta la liebre',
  'echar margaritas a los cerdos',
  'el buen paño en el arca se vende',
  'el dinero no da la felicidad',
  'el ojo del amo engorda el caballo',
  'el pez grande se come al chico',
  'el que calla otorga',
  'el que juega con fuego se quema',
  'el que mucho habla mucho yerra',
  'el que quiera peces que se moje',
  'el que se pica ajos come',
  'en abril lluvias mil',
  'en la variedad está el gusto',
  'en martes ni te cases ni te embarques',
  'entre bomberos no se pisan la manguera',
  'es mejor ser cabeza de ratón que cola de león',
  'estar hecho un mar de dudas',
  'gato con guantes no caza ratones',
  'hablar es plata y callar es oro',
  'hasta el mejor escribano echa un borrón',
  'hombre prevenido vale por dos',
  'la caridad bien entendida empieza por uno mismo',
  'la excepción confirma la regla',
  'la ignorancia es atrevida',
  'la lengua no tiene hueso pero rompe el cuerpo',
  'la necesidad hace maestros',
  'la palabra es plata y el silencio es oro',
  'la paciencia es la madre de la ciencia',
  'la vida es sueño',
  'las cosas claras y el chocolate espeso',
  'las cuentas claras conservan la amistad',
  'las malas noticias vuelan',
  'lo cortés no quita lo valiente',
  'lo que no mata engorda',
  'lo que bien empieza bien acaba',
  'lo que se ve no se pregunta',
  'los duelos con pan son menos',
  'más sabe el diablo por viejo que por diablo',
  'más vale caer en gracia que ser gracioso',
  'más vale que sobre y no que falte',
  'muchas manos en un plato hacen mucho garabato',
  'ni tanto que queme al santo ni tanto que no lo alumbre',
  'no es lo mismo predicar que dar trigo',
  'no hay atajo sin trabajo',
  'no hay mejor salsa que el hambre',
  'no hay quinto malo',
  'no se puede tener todo en esta vida',
  'no todo el monte es orégano',
  'nunca llueve a gusto de todos',
  'obras son amores y no buenas razones',
  'ojos que no ven tropiezan con todo',
  'para muestra basta un botón',
  'perro ladrador poco mordedor',
  'por la boca muere el pez',
  'querer es poder',
  'quien a hierro mata a hierro muere',
  'quien canta sus males espanta',
  'quien mucho duerme poco aprende',
  'quien no tiene cabeza tiene pies',
  'quien paga manda',
  'quien se fue a la villa perdió su silla',
  'quien tiene tejado de vidrio no tira piedras',
  'reír es el mejor remedio',
  'sarna con gusto no pica',
  'se dice el pecado pero no el pecador',
  'si quieres paz prepárate para la guerra',
  'tal para cual',
  'tanto tienes tanto vales',
  'tirar piedras sobre el propio tejado',
  'todo tiene solución menos la muerte',
  'tras la tempestad viene la calma',
  'un grano no hace granero pero ayuda al compañero',
  'una manzana al día mantiene al médico en la lejanía',
  'ver la paja en el ojo ajeno',
  'vísteme despacio que tengo prisa',
  'a enemigo que huye puente de plata',
  'a la cama no te irás sin saber una cosa más',
  'a quien dios se la dé san pedro se la bendiga',
  'antes se coge al mentiroso que al cojo',
  'cada gallo canta en su corral',
  'con pan y vino se anda el camino',
  'el que come y no convida tiene un sapo en la barriga',
  'el que ríe de último ríe mejor',
  'el sol sale para todos',
  'la memoria es la primera que se pierde',
  'no hay pan sin trabajo',
  'no se puede estar en misa y repicando',
  'quien no oye consejo no llega a viejo',
  'siempre hay un roto para un descosido',
  'una buena acción es la mejor oración',
  'a barriga llena corazón contento',
  'el saber es poder',
  'la risa es contagiosa',
  'el silencio es oro',
  'quien mucho corre pronto para',
  'a cada pajarillo le gusta su nidillo',
  'más vale un buen amigo que un pariente lejano',
  'la ropa sucia se lava en casa',
  'no hay mejor maestro que la experiencia',
  'cada cosa a su tiempo y los nabos en adviento',
  'el que no sabe es como el que no ve',
  'la codicia rompe el saco',
  'nadie escarmienta en cabeza ajena',
  'ni todo lo que se dice es verdad',
  'no hay mayor desprecio que no hacer aprecio',
  'a gran señor gran honor',
  'el trabajo bien hecho no tiene prisa',
  'quien no llora no mama',
  'a la ocasión la pintan calva',
  'lo que no se ve no se recuerda',
  'quien te quiere te hará reír',
  'cuando el gato no está los ratones bailan',
  'quien no sabe callar no sabe hablar',
  'del árbol caído todos hacen leña',
  'donde comen dos comen tres',
  'el que mucho abarca poco aprieta',
  'la ley entra por la casa',
  'no hay mal que cien años dure',
  'quien se acuesta con niños amanece mojado',
  'lo que hoy se piensa mañana se hace',
  'para el amor no hay edad',
  'quien da primero da dos veces',
  'con buen viento cualquiera navega',
  'las prisas nunca fueron buenas',
  'cada cosa en su sitio y un sitio para cada cosa',
  'de los errores se aprende',
  'el que nada debe nada teme',
  'el que sabe sabe y el que no aprende',
  'la verdad siempre sale a la luz',
  'no hay camino fácil hacia la cima',
  'las buenas cuentas hacen los buenos amigos',
  'lo que fácil viene fácil se va',
  'la confianza se gana con el tiempo',
  'no hay que dar por hecho lo que no está hecho',
  'un día es un día',
  'cuando hay hambre no hay pan duro',
  'primero es la obligación y luego la devoción',
  'la vida da muchas vueltas',
  'todo llega para quien sabe esperar',
  'no hay prisa que no acabe en tropiezo',
  'a veces menos es más',
  'quien nada arriesga nada teme',
  'hasta la mejor cocinera se le quema la sopa',
  'las palabras se las lleva el viento',
  'el respeto se gana no se exige',
  'el descanso también es parte del trabajo',
  'no hay mejor almohada que la conciencia tranquila',
  'donde hay cariño hay hogar',
  'un buen libro es un buen amigo',
  'el que parte primero llega primero',
  'con tiempo y paciencia todo llega',
  'lo bueno se hace esperar',
  'la ocasión hace al ladrón',
  'más vale una verdad amarga que una mentira dulce',
  'cada uno cosecha lo que siembra',
  'no todo el que llega tarde pierde',
  'la mejor defensa es un buen ataque',
  'los sueños se cumplen con esfuerzo',
  'no hay noche que no acabe',
];

const EN = [
  'actions speak louder than words',
  'the early bird catches the worm',
  'better late than never',
  'a picture is worth a thousand words',
  'every cloud has a silver lining',
  'practice makes perfect',
  'the grass is always greener on the other side',
  'do not count your chickens before they hatch',
  'a friend in need is a friend indeed',
  'an apple a day keeps the doctor away',
  'birds of a feather flock together',
  'do not put all your eggs in one basket',
  'the pen is mightier than the sword',
  'when in rome do as the romans do',
  'a watched pot never boils',
  'beggars cannot be choosers',
  'honesty is the best policy',
  'look before you leap',
  'no pain no gain',
  'rome was not built in a day',
  'the apple does not fall far from the tree',
  'there is no place like home',
  'time flies when you are having fun',
  'too many cooks spoil the broth',
  'two heads are better than one',
  'where there is a will there is a way',
  'you cannot judge a book by its cover',
  'absence makes the heart grow fonder',
  'all good things come to an end',
  'all that glitters is not gold',
  'curiosity killed the cat',
  'easy come easy go',
  'every dog has its day',
  'fortune favours the bold',
  'good things come to those who wait',
  'great minds think alike',
  'haste makes waste',
  'if it is not broken do not fix it',
  'ignorance is bliss',
  'it takes two to tango',
  'kill two birds with one stone',
  'laughter is the best medicine',
  'let sleeping dogs lie',
  'money does not grow on trees',
  'necessity is the mother of invention',
  'never say never',
  'no news is good news',
  'one good turn deserves another',
  'out of sight out of mind',
  'slow and steady wins the race',
  'the best things in life are free',
  'the customer is always right',
  'the squeaky wheel gets the grease',
  'there is no such thing as a free lunch',
  'to err is human to forgive divine',
  'what goes around comes around',
  'you reap what you sow',
  'a chain is only as strong as its weakest link',
  'a leopard cannot change its spots',
  'a rolling stone gathers no moss',
  'a stitch in time saves nine',
  'add insult to injury',
  'barking up the wrong tree',
  'beat around the bush',
  'bite off more than you can chew',
  'blood is thicker than water',
  'break the ice',
  'burn the midnight oil',
  'cross that bridge when you come to it',
  'cut corners to save time',
  'do not bite the hand that feeds you',
  'do not cry over spilt milk',
  'every man for himself',
  'give someone the benefit of the doubt',
  'go the extra mile',
  'hit the nail on the head',
  'in the heat of the moment',
  'it is raining cats and dogs',
  'jump on the bandwagon',
  'keep your chin up',
  'let the cat out of the bag',
  'like two peas in a pod',
  'make a long story short',
  'miss the boat',
  'once in a blue moon',
  'piece of cake',
  'pull yourself together',
  'read between the lines',
  'sit on the fence',
  'speak of the devil',
  'steal someone thunder',
  'take it with a grain of salt',
  'the ball is in your court',
  'the last straw',
  'through thick and thin',
  'under the weather',
  'we will cross that bridge later',
  'when pigs fly',
  'you can say that again',
  'a bird in the hand is worth two in the bush',
  'a penny saved is a penny earned',
  'all is fair in love and war',
  'an ounce of prevention is worth a pound of cure',
  'as you make your bed so you must lie in it',
  'beauty is in the eye of the beholder',
  'better safe than sorry',
  'charity begins at home',
  'cleanliness is next to godliness',
  'do not judge a book by its cover',
  'do not look a gift horse in the mouth',
  'early to bed and early to rise',
  'familiarity breeds contempt',
  'first come first served',
  'hope for the best and prepare for the worst',
  'if you cannot beat them join them',
  'in for a penny in for a pound',
  'it is never too late to learn',
  'keep your friends close and your enemies closer',
  'knowledge is power',
  'learn to walk before you run',
  'life is what you make it',
  'lightning never strikes twice',
  'make hay while the sun shines',
  'many hands make light work',
  'never look a gift horse in the mouth',
  'old habits die hard',
  'one man trash is another man treasure',
  'people who live in glass houses should not throw stones',
  'practice what you preach',
  'seeing is believing',
  'silence is golden',
  'strike while the iron is hot',
  'the more the merrier',
  'the proof of the pudding is in the eating',
  'the road to hell is paved with good intentions',
  'there is no time like the present',
  'those who play with fire get burned',
  'tomorrow is another day',
  'two wrongs do not make a right',
  'variety is the spice of life',
  'well begun is half done',
  'what you see is what you get',
  'you cannot have your cake and eat it',
  'you cannot make an omelette without breaking eggs',
  'you live and learn',
  'a bad workman blames his tools',
  'a fool and his money are soon parted',
  'a journey of a thousand miles begins with a single step',
  'a little knowledge is a dangerous thing',
  'a man is known by the company he keeps',
  'after a storm comes a calm',
  'all roads lead to rome',
  'an idle mind is the devil workshop',
  'any port in a storm',
  'ask no questions and hear no lies',
  'bad news travels fast',
  'behind every great man there is a great woman',
  'brevity is the soul of wit',
  'clothes do not make the man',
  'cold hands warm heart',
  'discretion is the better part of valour',
  'do as i say not as i do',
  'do not throw the baby out with the bathwater',
  'every little bit helps',
  'every rose has its thorn',
  'eyes are the window to the soul',
  'faint heart never won fair lady',
  'fight fire with fire',
  'give credit where credit is due',
  'good fences make good neighbours',
  'half a loaf is better than none',
  'he who hesitates is lost',
  'he who laughs last laughs longest',
  'history repeats itself',
  'if the shoe fits wear it',
  'if you want a thing done well do it yourself',
  'it is always darkest before the dawn',
  'it is the thought that counts',
  'it takes a village to raise a child',
  'keep your eyes on the prize',
  'kindness costs nothing',
  'least said soonest mended',
  'less is more',
  'let bygones be bygones',
  'live and let live',
  'love conquers all',
  'love is blind',
  'manners maketh man',
  'misery loves company',
  'more haste less speed',
  'nothing ventured nothing gained',
  'one swallow does not make a summer',
  'opportunity does not knock twice',
  'patience is a virtue',
  'penny wise pound foolish',
  'prevention is better than cure',
  'pride comes before a fall',
  'put your money where your mouth is',
  'revenge is a dish best served cold',
  'still waters run deep',
  'talk is cheap',
  'the bigger they are the harder they fall',
  'the devil is in the details',
  'the exception proves the rule',
  'the first step is the hardest',
  'the sky is the limit',
  'the truth will out',
  'there are plenty more fish in the sea',
  'there is safety in numbers',
  'time and tide wait for no man',
  'time is money',
  'truth is stranger than fiction',
  'walls have ears',
  'waste not want not',
  'we all make mistakes',
  'what is done is done',
  'while there is life there is hope',
  'you are never too old to learn',
  'you cannot teach an old dog new tricks',
  'you get what you pay for',
  'you win some you lose some',
  'a change is as good as a rest',
  'a good beginning makes a good ending',
  'a problem shared is a problem halved',
  'all work and no play makes jack a dull boy',
  'better the devil you know',
  'boys will be boys',
  'count your blessings',
  'do not judge by appearances',
  'do not make a mountain out of a molehill',
  'do not put the cart before the horse',
  'do not rock the boat',
  'do not wash your dirty linen in public',
  'do unto others as you would have them do unto you',
  'every man has his price',
  'every picture tells a story',
  'give a dog a bad name',
  'hindsight is always twenty twenty',
  'home is where the heart is',
  'if at first you do not succeed try again',
  'it is better to give than to receive',
  'it never rains but it pours',
  'jack of all trades master of none',
  'keep something for a rainy day',
  'let the chips fall where they may',
  'like father like son',
  'look on the bright side',
  'make the best of a bad job',
  'money talks',
  'no man is an island',
  'one thing at a time',
  'out of the frying pan into the fire',
  'rome was not built in one day',
  'the best defence is a good offence',
  'the end justifies the means',
  'the show must go on',
  'the wheel turns',
  'there is honour among thieves',
  'think before you speak',
  'tit for tat',
  'united we stand divided we fall',
  'when the cat is away the mice will play',
  'you are what you eat',
  'you cannot please everyone',
  'you snooze you lose',
  'a friend to all is a friend to none',
  'a house divided cannot stand',
  'a word to the wise is enough',
  'burn your bridges behind you',
  'do not bite off more than you can chew',
  'every cloud has its silver lining',
  'fools rush in where angels fear to tread',
  'hunger is the best sauce',
  'it is no use crying over spilt milk',
  'little strokes fell great oaks',
  'many a true word is spoken in jest',
  'no man can serve two masters',
  'the calm before the storm',
  'the pot calling the kettle black',
  'the tip of the iceberg',
  'you have to take the rough with the smooth',
  'a good name is better than riches',
  'a soft answer turns away wrath',
  'all things come to those who wait',
  'an army marches on its stomach',
  'as you sow so shall you reap',
  'better an egg today than a hen tomorrow',
  'better to light a candle than curse the darkness',
  'do not spoil the ship for a penny of tar',
  'even a worm will turn',
  'every jack has his jill',
  'experience is the best teacher',
  'give and take is fair play',
  'good things come in small packages',
  'great oaks from little acorns grow',
  'if wishes were horses beggars would ride',
  'in the land of the blind the one eyed man is king',
  'it is easy to be wise after the event',
  'let not the sun go down on your wrath',
  'life is not all beer and skittles',
  'look after the pennies and the pounds will look after themselves',
  'make love not war',
  'many a mickle makes a muckle',
  'never put off till tomorrow what you can do today',
  'no rest for the wicked',
  'none so deaf as those who will not hear',
  'nothing succeeds like success',
  'one hand washes the other',
  'possession is nine tenths of the law',
  'rob peter to pay paul',
  'set a thief to catch a thief',
  'spare the rod and spoil the child',
  'the child is father of the man',
  'the darkest hour is just before the dawn',
  'the labourer is worthy of his hire',
  'the longest journey begins with a single step',
  'there are two sides to every question',
  'there is many a slip between cup and lip',
  'there is no fool like an old fool',
  'there is no smoke without fire',
  'to the victor go the spoils',
  'two is company three is a crowd',
  'use it or lose it',
  'walk the walk and talk the talk',
  'what cannot be cured must be endured',
  'you cannot get blood out of a stone',
  'you cannot unscramble eggs',
  'youth is wasted on the young',
  'a cat may look at a king',
  'a dog is a man best friend',
  'a fish rots from the head down',
  'a good laugh and a long sleep are the best cures',
  'a miss is as good as a mile',
  'a rising tide lifts all boats',
  'a stumble may prevent a fall',
  'accidents will happen in the best regulated families',
  'always look on the bright side of life',
  'back to the drawing board',
  'better to ask the way than go astray',
  'do not throw good money after bad',
  'do not try to run before you can walk',
  'do not upset the apple cart',
  'east or west home is best',
  'empty vessels make the most noise',
  'enough is as good as a feast',
  'every path has its puddle',
  'every stick has two ends',
  'eat drink and be merry',
  'first things first',
  'give a man enough rope and he will hang himself',
  'grasp all lose all',
  'he who pays the piper calls the tune',
  'if you pay peanuts you get monkeys',
  'it is a long lane that has no turning',
  'it takes all sorts to make a world',
  'keep your powder dry',
  'let the buyer beware',
  'like water off a duck back',
  'little pitchers have big ears',
  'many a little makes a mickle',
  'mind your own business',
  'moderation in all things',
  'no man is a hero to his valet',
  'nothing is certain but death and taxes',
  'oil and water do not mix',
  'one man meat is another man poison',
  'out of the mouths of babes',
  'put your best foot forward',
  'rome will not be built in a day',
  'see no evil hear no evil speak no evil',
  'slow but sure wins the race',
  'the best laid plans go astray',
  'the cobbler children have no shoes',
  'the early worm gets eaten by the bird',
  'the leopard does not change its spots',
  'the morning sun never lasts a day',
  'the way to a man heart is through his stomach',
  'there is a time and a place for everything',
  'there is no accounting for taste',
  'things are not always what they seem',
  'those who do not learn from history repeat it',
  'you can lead a horse to water but you cannot make it drink',
  'you scratch my back and i will scratch yours',
  'you never know what you can do until you try',
];

const strip = (s) => s.normalize('NFD').replace(/[̀-ͯ]/g, '');
const clean = (s) => s.trim().toLowerCase().replace(/\s+/g, ' ');
const letters = (s) => strip(s).replace(/[^a-zñ]/g, '').length;

function build(language, source) {
  const seen = new Set();
  const kept = [];
  const dropped = [];
  for (const raw of source) {
    const phrase = clean(raw);
    const key = strip(phrase).replace(/ñ/g, 'n');
    const words = phrase.split(' ');
    const total = letters(phrase);
    const ok =
      /^[a-záéíóúüñ ]+$/.test(phrase) &&
      words.length >= 4 &&
      words.length <= 8 &&
      total >= 16 &&
      total <= 42 &&
      !seen.has(key);
    if (!ok) {
      dropped.push(`${phrase} (${words.length} words, ${total} letters${seen.has(key) ? ', duplicate' : ''})`);
      continue;
    }
    seen.add(key);
    kept.push(phrase);
  }
  writeFileSync(
    path.join(out, `phrases.${language}.json`),
    JSON.stringify({ language, phrases: kept }, null, 2) + '\n',
  );
  console.log(`${language}: ${kept.length} phrases kept, ${dropped.length} dropped`);
  for (const line of dropped) console.log(`  - ${line}`);
}

build('es', ES);
build('en', EN);
